# jaxlib wants clang on all platforms
c_compiler:
  - clang
cxx_compiler:
  - clangxx  # [unix]
  - clang  # [win]

gpu_variant:
  - cpu
# TODO: Skip CUDA builds for now since this package requires at least GCC 14 to build and we don't have CUDA built
#       with GCC 14 yet.
#  - cuda-12                    # [(linux and x86_64)]

cuda_compiler_version:
  - None
# TODO: Skip CUDA builds for now since this package requires at least GCC 14 to build and we don't have CUDA built
#       with GCC 14 yet.
#  - 12.4                       # [(linux and x86_64)]
cuda_compiler:                 # [(linux and x86_64)]
  - cuda-nvcc                  # [(linux and x86_64)]

cudnn:                         # [(linux and x86_64)]
  - '9.1.1.17'                 # [(linux and x86_64)]
nccl:                          # [(linux and x86_64)]
  - '2.21.5.1'                 # [(linux and x86_64)]

zip_keys:                      # [(linux and x86_64)]
  -                            # [(linux and x86_64)]
    - gpu_variant              # [(linux and x86_64)]
    - cuda_compiler_version    # [(linux and x86_64)]

# The latest version of abseil and friends
# From the staging channel: https://staging.continuum.io/pbp/protobuf-6.33.0-build-4
libabseil:
  - '20250814.1'               # [unix]
libgrpc:
  - '1.74.1'                   # [unix]
libprotobuf:
  - '6.33.0'                   # [unix]
